version: "{build}"

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: 0.12

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install sass
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - bower install

test_script:
  - node --version && npm --version
  - npm start

build: off

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json # npm cache
  - node_modules -> package.json                                # local npm modules